config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :lms_settings do
  collection do
    get 'generate_leave_history'
  end
  member do
    get 'start'
  end
end

resources :lms_leave_accounts, :only => [:index, :create, :update]

resources :lms_dashboards do
	
end

resources :lms_reports, :only => [:index] do
  member do
  end
  collection do
    get 'month'
    get 'ytd'
    get 'year'
  end
end
get '/lms_reports/:user_id/month_detailed/:year/:month', :to => 'lms_reports#month_detailed', :as => 'month_detailed_lms_report'
get '/lms_reports/:user_id/ytd_detailed/:year/:month', :to => 'lms_reports#ytd_detailed', :as => 'ytd_detailed_lms_report'
get '/lms_reports/:user_id/year/:year', :to => 'lms_reports#year_detailed', :as => 'year_detailed_lms_report'

resources :lms_leave_types do
  member do
    get 'activate'
    get 'deactivate'
  end
end
resources :lms_leaves do
  collection do
    get 'pending'
    get 'approved'
    get 'rejected'
    get 'cancelled'
    post 'deduct'
  end
  member do
    get 'approve'
    get 'reject'
    get 'proces'
  end
end
resources :lms_public_holidays

app/controllers/lms_reports_controller.rb
class LmsReportsController < ApplicationController
  unloadable
  include LeaveManagementSystem::Controller

  before_filter :lms_authorize
  before_filter :find_leave_settings_and_leave_types, :except => [:index]
  before_filter :find_employees_leave_histories, :only => [:month, :year, :ytd]
  before_filter :find_employee_leaves, :only => [:month_detailed, :year_detailed, :ytd_detailed]
  
  def index

  end
  
  def month

  end
  
  def year

  end
  
  def ytd

  end
  
  def month_detailed
    respond_to do |format|
      format.js
    end
  end
  
  def year_detailed
    respond_to do |format|
      format.js
    end 
  end
  
  def ytd_detailed
    respond_to do |format|
      format.js
    end
  end
  
  private
  def find_leave_settings_and_leave_types
    @years = LmsYearlySetting.order("year DESC").map(&:year)
    if @years.present?
      @year = (params[:year] || Date.today.year).to_i
      @year = @years.include?(@year) ? @year : @years.first
      unless ['year', 'year_detailed'].include? action_name
        @month = params[:month] || Date.today.month
      else
        @month = 12
      end
      @yearly_settings = LmsYearlySetting.where(["year = ?", @year]).first
      find_leave_types
    else
      render :action => :no_data
    end
  end
  
  def find_employee_leaves
    begin
      @employee = Employee.find params[:user_id]
      r_period = case action_name
	  when :month_detailed
	        LmsLeaveType::MONTH
	  else
	       LmsLeaveType::YEAR
	  end
      @leaves = @employee.leaves(@year, @month, LmsLeaveStatus::PROCESSED, r_period, LmsLeave::LEAVE)
      @wfh = @employee.leaves(@year, @month, LmsLeaveStatus::PROCESSED, r_period, LmsLeave::WFH) 
    rescue ActiveRecord::RecordNotFound
      render_404
    end
  end
  
  def find_employees_leave_histories
    @employees = LeaveManagementSystem.employees_with_role LeaveManagementSystem::ROLES[:al]
    @leave_histories = []
    r_period = case action_name.to_sym
                 when :month
                   LmsLeaveType::MONTH
                 else
                   LmsLeaveType::YEAR
               end
    @employees.each do|u|
      leave_history = u.leave_history(@active_leave_types.map(&:identifier), @year, @month, r_period)
      next unless leave_history
      @leave_histories << leave_history
    end
  end
end

app/helpers/lms_reports_helper.rb
module LmsReportsHelper
end

app/views/lms_reports/_detailed_report.html.erb
<% 
  @year, @month = @year.to_i, @month.to_i
%>
<div id='detailed-report'>
<div id='heading'>
  <h3 class='title'>
  <%= 
    case action_name
      when 'month_detailed'
        "#{Date.new(@year, @month).strftime('%b %Y')} Detailed Report"
      when 'year_detailed'
        "#{Date.new(@year, @month).strftime('%Y')} Detailed Report"
      when 'ytd_detailed'
        "#{Date.new(@year, 1).strftime('%b %Y')} - #{Date.new(@year, @month).strftime('%b %Y')} Detailed Report"
    end
  %>
  </h3>
</div>
<div id='emp-info' class='box'>
<h3>Employee Info</h3>
<div><span>Name </span><%= @employee.name %></div>
<% if @employee.respond_to? :department %><div><span>Department </span><%= @employee.department.name %></div><% end %>
<% if @employee.respond_to? :job_title %>
      <div><span>Designation </span><%= @employee.job_title %></div><% end %><br/>
</div>
<div id='leave-detail' class='box'>
<h3>Leaves Detail</h3>
<div id='leave-summ'>
    <% if @yearly_settings.carry_forward %>
      <div><span>Carry Forward </span>
        <% sum_leaves = @leaves.map(&:ded_carry_forward).sum %>
        <%= sum_leaves.is_a?(Fixnum) ? sum_leaves : truncate_trailing_zero(sum_leaves) %>
      </div>
  <% end %>
    <%  @active_leave_types.each do |lt| %>
      <div><span><%= lt.name %> </span><% sum_leaves= @leaves.map(&"ded_#{lt.identifier}".to_sym).sum %><%= sum_leaves.is_a?(Fixnum) ? sum_leaves : truncate_trailing_zero(sum_leaves) %></div>
    <% end %>
    <div><span>LOP </span><% sum_leaves= @leaves.map(&:lop).sum %>
      <%= sum_leaves.is_a?(Fixnum) ? sum_leaves : truncate_trailing_zero(sum_leaves) %></div>
</div>
<br/>
<% if @leaves.present? %>
<div class='table'>
<table>
  <tr>
    <th style="width:11%">From Date</th>
    <th style="width:11%">To Date</th>
    <th style="width:5%">Leave Type</th>
    <th style="width:20%">Reason</th>
    <th style="width:5%">No of days</th>
    <th style="width:10%">Approved By</th>
    <th style="width:20%">Days</th>
    <th style="width:18%">Deduction Detail</th>
  </tr>
  <% @leaves.each do |leave| %>
    <tr class="<%= cycle('odd', 'even') %>">
      <td><%= leave.from_date.strftime('%d %b %Y') %></td>
      <td><%= leave.to_date.strftime('%d %b %Y') %></td>
      <td><%= LmsLeaveCategory.all[leave.leave_category_id] %></td>
      <td><%= leave.reason %></td>
      <td><%= truncate_trailing_zero(leave.no_of_days) %></td>
      <td><%= Employee.find leave.approved_by %></td>
      <td><% if leave.full_days.present? %><b>Full Days:</b><br/><%= leave.full_days %><br/><% end %><% if leave.half_days.present? %><b>Half Days:</b><br/><%= leave.half_days %><% end %></td>
      <td>
        <%  @active_leave_types.each do |lt| %>
	  <% if leave.send("ded_#{lt.identifier}") > 0 %>
	    <%= lt.name%> : <%= truncate_trailing_zero(leave.send("ded_#{lt.identifier}")) %><br/>
	  <% end %>
	<% end %>
	<% if leave.ded_carry_forward > 0 %>
	  Carry Forward : <%= truncate_trailing_zero(leave.ded_carry_forward) %><br/>
	<% end %>
	<% if leave.lop > 0 %>
	  LOP : <%= truncate_trailing_zero(leave.lop) %><br/>
	<% end %>
     </td>
    </tr>
  <% end %>
</table>
</div>
<% else %>
  <p class="nodata">No data</p>
<% end %>
</div>
<% if @yearly_settings.work_from_home %>
  <div id='wfh-detail' class='box'>
  <h3>Work From Home Detail</h3>
  <div id='wfh-summ'>
      <div><span>Work from home </span><% sum_wfh= @wfh.map(&:ded_wfh).sum %><%= sum_wfh.is_a?(Fixnum) ? sum_wfh : truncate_trailing_zero(sum_wfh) %></div>
  </div>
  <br/>
  <% if @wfh.present? %>
  <div class='table'>
  <table>
    <tr>
      <th style="width:11%">From Date</th>
      <th style="width:11%">To Date</th>
      <th style="width:5%">Leave Type</th>
      <th style="width:20%">Reason</th>
      <th style="width:5%">No of days</th>
      <th style="width:10%">Approved By</th>
      <th style="width:20%">Days</th>
      <th style="width:18%">Deduction Detail</th>
    </tr>
    <% @wfh.each do |wfh| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td><%= wfh.from_date.strftime('%d %b %Y') %></td>
        <td><%= wfh.to_date.strftime('%d %b %Y') %></td>
        <td><%= LmsLeaveCategory.all[wfh.leave_category_id] %></td>
        <td><%= wfh.reason %></td>
        <td><%= truncate_trailing_zero(wfh.no_of_days) %></td>
        <td><%= Employee.find wfh.approved_by %></td>
        <td><% if wfh.full_days.present? %><b>Full Days:</b><br/><%= wfh.full_days %><br/><% end %><% if wfh.half_days.present? %><b>Half Days:</b><br/><%= wfh.half_days %><% end %></td>
        <td><%= truncate_trailing_zero(wfh.ded_wfh) %></td>
      </tr>
    <% end %>
  </table>
  </div>
  <% else %>
    <p class="nodata">No data</p>
  <% end %>
  </div>
<% end %>
</div>
<script>
$('table tr.odd, table tr.even').click(function(){
	$('table tr.odd.selected-row, table tr.even.selected-row').removeClass('selected-row');
	$(this).addClass('selected-row');
});
</script>

app/views/lms_reports/_menu.html.erb
<div id='lms-report-menu'>
  <a href='<%= month_lms_reports_path %>' class="<%= action_name.eql?('month') ? 'active' : '' %>">Monthly</a>
  <a href='<%= ytd_lms_reports_path %>' class="<%= action_name.eql?('ytd') ? 'active' : '' %>">YTD</a>
  <a href='<%= year_lms_reports_path %>' class="<%= action_name.eql?('year') ? 'active' : '' %>">Yearly</a>
</div>

app/views/lms_reports/month.html.erb
<%= render :partial => "/partials/top_menu" %>
<% 
  months = l('date.abbr_month_names').dup
  months.shift
  i = 0
  will_be_carry_forwarded = @yearly_settings.carry_forward
  leaves_taken_cols = 2+@active_leave_types.count+(will_be_carry_forwarded ? 1 : 0)
  available_leaves_cols = 1+@active_leave_types.count+(will_be_carry_forwarded ? 1 : 0)
%>
<div style="margin:20px 20px;" class="lms_box_wrapper">
  <%= render :partial => 'menu' %>
  <div class="content">
    <div style="text-align:center;padding:20px 0 10px 0;" class="period">
      <div style="text-align:center;" class="title">
    <h3 style='padding:0 15px 0 30px;color:#555;'><%= Date.civil(@year.to_i, @month.to_i).strftime('%B %Y') %> Report</h3>
  </div>
  <div style="float:left;">
    <%= form_tag "/lms_reports/month", {:method => :get, :id => 'lms_report'} do |f| %>
    Year <%= select_tag :year, options_for_select(@years, @year), :onchange => "$('#lms_report').submit();" %> Month <%= select_tag :month, options_for_select(months.collect {|m| [m, i += 1] }, @month), :onchange => "$('#lms_report').submit();" %>
    <% end %>
    </div>
    </div>
    <div style="clear:both;padding:0 30px;" class="report_wrapper">
      <% if @leave_histories.present? %>
        <table>
          <tr>
            <th rowspan=2>Employee Name</th>
            <th colspan=<%= leaves_taken_cols %>>Leaves Taken</th>
  	    <% if @yearly_settings.work_from_home %><th colspan=3>WFH</th><% end %>
  	    <th rowspan=2>Details</th>
          </tr>
    
          <tr>
            <% if will_be_carry_forwarded %><th class="sub_heading">Carry Forward</th><% end %>
  	  <% @active_leave_types.each do |lt| %><th class="sub_heading"><%= lt.name %></th><% end %>
  	  <th class="sub_heading">LOP</th>
  	  <th class="sub_heading">Total</th>
	  <% if @yearly_settings.work_from_home %>
  	    <th class="sub_heading">Used</th>
  	    <th class="sub_heading">Available</th>
  	    <th class="sub_heading">Total</th>
	  <% end %>
          </tr>
          <% @leave_histories.each do |lh| %>
          <tr class="<%= cycle('odd', 'even') %>">
            <td><%= lh.emp_name %></td>
  	  <% if will_be_carry_forwarded %><td><%= truncate_trailing_zero(lh.ded_carry_forward) %></td><% end %>
  	  <% @active_leave_types.each do |lt| %><td><%= truncate_trailing_zero(lh.send("ded_#{lt.identifier}")) %></td><% end %>
  	  <td><%= truncate_trailing_zero(lh.lop) %></td>
  	  <td><%= truncate_trailing_zero((lh.total_leaves_taken + lh.lop)) %></td>
	  <% if @yearly_settings.work_from_home %>
  	    <td><%= truncate_trailing_zero(lh.ded_wfh) %></td>
  	    <td><%= truncate_trailing_zero((lh.tot_wfh - lh.ded_wfh)) %></td>
  	    <td><%= truncate_trailing_zero(lh.tot_wfh) %></td>
	  <% end %>
  	  <td><%= link_to 'Details', month_detailed_lms_report_path(lh.user_id, @year, @month), :remote => true %></td>
          </tr>
          <% end %>
        </table>
      <% else %>
        <p class="nodata">No data</p>
      <% end %>
    </div>
  </div>
</div>

app/views/lms_reports/month_detailed.js.erb
$('#ajax-modal').html('<%= escape_javascript(render :partial => 'lms_reports/detailed_report') %>');
showModal('ajax-modal', '900px');

app/views/lms_reports/no_data.html.erb
<%= render :partial => "/partials/top_menu" %>
<p class="nodata">No data</p>

app/views/lms_reports/year.html.erb
<%= render :partial => "/partials/top_menu" %>
<% 
  will_be_carry_forwarded = @yearly_settings.carry_forward
  leaves_taken_cols = 2+@active_leave_types.count+(will_be_carry_forwarded ? 1 : 0)
  available_leaves_cols = 1+@active_leave_types.count+(will_be_carry_forwarded ? 1 : 0)
%>
<div style="margin:20px 20px;" class="lms_box_wrapper">
  <%= render :partial => 'menu' %>
  <div class="content">
    <div style="text-align:center;padding:20px 0 10px 0;" class="period">
      <div style="text-align:center;" class="title">
    <h3 style='float:left;padding:0 15px 0 30px;color:#555;'><%= Date.civil(@year.to_i, @month.to_i).strftime('%Y') %> Report</h3>
  </div>
  <div style="float:left;">
    <%= form_tag "/lms_reports/year", {:method => :get, :id => 'lms_report'} do |f| %>
    Year <%= select_tag :year, options_for_select(@years, @year), :onchange => "$('#lms_report').submit();" %>
    <% end %>
    </div>
    </div>
    <div style="clear:both;padding:0 30px;" class="report_wrapper">
      <% if @leave_histories.present? %>
        <table>
          <tr>
            <th rowspan=2>Employee Name</th>
            <th colspan=<%= leaves_taken_cols %>>Leaves Taken</th>
  	  <th colspan=<%= leaves_taken_cols - 1 %>>Available Leaves</th>
  	  <% if @yearly_settings.work_from_home %><th colspan=2>WFH</th><% end %>
  	  <th rowspan=2>Details</th>
          </tr>
    
          <tr>
            <% if will_be_carry_forwarded %><th class="sub_heading">Carry Forward</th><% end %>
  	  <% @active_leave_types.each do |lt| %><th class="sub_heading"><%= lt.name %></th><% end %>
  	  <th class="sub_heading">LOP</th>
  	  <th class="sub_heading">Total</th>
  	  <% if will_be_carry_forwarded %><th class="sub_heading">Carry Forward</th><% end %>
  	  <% @active_leave_types.each do |lt| %><th class="sub_heading"><%= lt.name %></th><% end %>
  	  <th class="sub_heading">Total</th>
	  <% if @yearly_settings.work_from_home %>
  	    <th class="sub_heading">Used</th>
  	    <th class="sub_heading">Total</th>
	  <% end %>
          </tr>
          <% @leave_histories.each do |lh| %>
          <tr class="<%= cycle('odd', 'even') %>">
            <td><%= lh.emp_name %></td>
  	  <% if will_be_carry_forwarded %><td><%= truncate_trailing_zero(lh.ded_carry_forward) %></td><% end %>
  	  <% @active_leave_types.each do |lt| %><td><%= truncate_trailing_zero(lh.send("ded_#{lt.identifier}")) %></td><% end %>
  	  <td><%= truncate_trailing_zero(lh.lop) %></td>
  	  <td><%= truncate_trailing_zero((lh.total_leaves_taken + lh.lop)) %></td>
  	  <% if will_be_carry_forwarded %><td><%= truncate_trailing_zero((lh.tot_carry_forward - lh.ded_carry_forward)) %><% end %>
  	  <% @active_leave_types.each do |lt| %><td><%= truncate_trailing_zero((lh.send("tot_#{lt.identifier}") - lh.send("ded_#{lt.identifier}"))) %></td><% end %>
  	  <td><%= truncate_trailing_zero((lh.total_leaves - lh.total_leaves_taken)) %></td>
	  <% if @yearly_settings.work_from_home %>
  	    <td><%= truncate_trailing_zero(lh.ded_wfh) %></td>
  	    <td><%= truncate_trailing_zero(lh.acc_wfh) %></td>
	  <% end %>
  	  <td><%= link_to 'Details', year_detailed_lms_report_path(lh.user_id, @year), :remote => true %></td>
          </tr>
          <% end %>
        </table>
      <% else %>
        <p class="nodata">No data</p>
      <% end %>
    </div>
  </div>
</div>

app/views/lms_reports/year_detailed.js.erb
$('#ajax-modal').html('<%= escape_javascript(render :partial => 'lms_reports/detailed_report') %>');
showModal('ajax-modal', '900px');

app/views/lms_reports/ytd.html.erb
<%= render :partial => "/partials/top_menu" %>
<% 
  months = l('date.abbr_month_names').dup
  months.shift
  i = 0
  will_be_carry_forwarded = @yearly_settings.carry_forward
  leaves_taken_cols = 2+@active_leave_types.count+(will_be_carry_forwarded ? 1 : 0)
  available_leaves_cols = 1+@active_leave_types.count+(will_be_carry_forwarded ? 1 : 0)
%>
<div style="margin:20px 20px;" class="lms_box_wrapper">
  <%= render :partial => 'menu' %>
  <div class="content">
    <div style="text-align:center;padding:20px 0 10px 0;" class="period">
      <div style="text-align:center;" class="title">
    <h3 style='padding:0 15px 0 30px;color:#555;'><%= Date.civil(@year.to_i, 1).strftime('%B %Y') %> - <%= Date.civil(@year.to_i, @month.to_i).strftime('%B %Y') %> Report</h3>
  </div>
  <div style="float:left;">
    <%= form_tag "/lms_reports/ytd", {:method => :get, :id => 'lms_report'} do |f| %>
    Year <%= select_tag :year, options_for_select(@years, @year), :onchange => "$('#lms_report').submit();" %> Month <%= select_tag :month, options_for_select(months.collect {|m| [m, i += 1] }, @month), :onchange => "$('#lms_report').submit();" %>
    <% end %>
    </div>
    </div>
    <div style="clear:both; padding:0 30px;" class="report_wrapper">
      <% if @leave_histories.present? %>
        <table>
          <tr>
            <th rowspan=2>Employee Name</th>
            <th colspan=<%= leaves_taken_cols %>>Leaves Taken</th>
  	  <th colspan=<%= leaves_taken_cols - 1 %>>Available Leaves</th>
  	  <% if @yearly_settings.work_from_home %><th colspan=2>WFH</th><% end %>
  	  <th rowspan=2>Details</th>
          </tr>
    
          <tr>
            <% if will_be_carry_forwarded %><th class="sub_heading">Carry Forward</th><% end %>
  	  <% @active_leave_types.each do |lt| %><th class="sub_heading"><%= lt.name %></th><% end %>
  	  <th class="sub_heading">LOP</th>
  	  <th class="sub_heading">Total</th>
  	  <% if will_be_carry_forwarded %><th class="sub_heading">Carry Forward</th><% end %>
  	  <% @active_leave_types.each do |lt| %><th class="sub_heading"><%= lt.name %></th><% end %>
  	  <th class="sub_heading">Total</th>
	  <% if @yearly_settings.work_from_home %>
  	    <th class="sub_heading">Used</th>
  	    <th class="sub_heading">Total</th>
	  <% end %>
          </tr>
          <% @leave_histories.each do |lh| %>
          <tr class="<%= cycle('odd', 'even') %>">
            <td><%= lh.emp_name %></td>
  	  <% if will_be_carry_forwarded %><td><%= truncate_trailing_zero(lh.ded_carry_forward) %></td><% end %>
  	  <% @active_leave_types.each do |lt| %><td><%= truncate_trailing_zero(lh.send("ded_#{lt.identifier}")) %></td><% end %>
  	  <td><%= truncate_trailing_zero(lh.lop) %></td>
  	  <td><%= truncate_trailing_zero((lh.total_leaves_taken + lh.lop)) %></td>
  	  <% if will_be_carry_forwarded %><td><%= truncate_trailing_zero((lh.tot_carry_forward - lh.ded_carry_forward)) %><% end %>
  	  <% @active_leave_types.each do |lt| %><td><%= truncate_trailing_zero((lh.send("tot_#{lt.identifier}") - lh.send("ded_#{lt.identifier}"))) %></td><% end %>
  	  <td><%= truncate_trailing_zero((lh.total_leaves - lh.total_leaves_taken)) %></td>
	  <% if @yearly_settings.work_from_home %>
  	    <td><%= truncate_trailing_zero(lh.ded_wfh) %></td>
  	    <td><%= truncate_trailing_zero(lh.acc_wfh) %></td>
	  <% end %>
  	  <td><%= link_to 'Details', ytd_detailed_lms_report_path(lh.user_id, @year, @month), :remote => true %></td>
          </tr>
          <% end %>
        </table>
      <% else %>
        <p class="nodata">No data</p>
      <% end %>
    </div>
  </div>
</div>

app/views/lms_reports/ytd_detailed.js.erb
$('#ajax-modal').html('<%= escape_javascript(render :partial => 'lms_reports/detailed_report') %>');
showModal('ajax-modal', '900px');