config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :lms_settings do
  collection do
    get 'generate_leave_history'
  end
  member do
    get 'start'
  end
end

resources :lms_leave_accounts, :only => [:index, :create, :update]

resources :lms_dashboards do
	
end

resources :lms_reports, :only => [:index] do
  member do
  end
  collection do
    get 'month'
    get 'ytd'
    get 'year'
  end
end
get '/lms_reports/:user_id/month_detailed/:year/:month', :to => 'lms_reports#month_detailed', :as => 'month_detailed_lms_report'
get '/lms_reports/:user_id/ytd_detailed/:year/:month', :to => 'lms_reports#ytd_detailed', :as => 'ytd_detailed_lms_report'
get '/lms_reports/:user_id/year/:year', :to => 'lms_reports#year_detailed', :as => 'year_detailed_lms_report'

resources :lms_leave_types do
  member do
    get 'activate'
    get 'deactivate'
  end
end
resources :lms_leaves do
  collection do
    get 'pending'
    get 'approved'
    get 'rejected'
    get 'cancelled'
    post 'deduct'
  end
  member do
    get 'approve'
    get 'reject'
    get 'proces'
  end
end
resources :lms_public_holidays

app/controllers/lms_leave_types_controller.rb
class LmsLeaveTypesController < ApplicationController
  unloadable
  include LeaveManagementSystem::Controller

  before_filter :lms_authorize
  before_filter :find_leave_type, :only => [:edit, :update, :activate, :deactivate, :destroy]
  before_filter :find_current_year_settings, :only => [:create, :update, :activate, :deactivate, :destroy]
  
  def new
    @leave_type = LmsLeaveType.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @leave_type = LmsLeaveType.new
    @leave_type.safe_attributes = lms_leave_type_params
    if @leave_type.save
    find_leave_types
    respond_to do |format|
      format.js
    end
    else
    respond_to do |format|
      format.js {render :action => :new}
    end
    end
  end

  def show
  end

  def edit
    respond_to do |format|
      format.js
    end  
  end

  def update
    @leave_type.safe_attributes = lms_leave_type_params
    if @leave_type.save
    find_leave_types
    respond_to do |format|
      format.js
    end
    else
    respond_to do |format|
      format.js {render :action => :edit}
    end
    end
  end

  def activate
    if @leave_type && @yearly_settings
      @yearly_settings.leave_types << @leave_type
      @yearly_settings.update_leave_type @leave_type
    end
    find_leave_types
    respond_to do |format|
      format.html{
        redirect_to lms_settings_path
      }
      format.js
    end
  end
  
  def deactivate
    if @leave_type && @yearly_settings
      @yearly_settings.leave_types = @yearly_settings.leave_types.where(["lms_leave_type_id != ?", @leave_type.id])
      @yearly_settings.clear_leave_type @leave_type
    end
    find_leave_types
    respond_to do |format|
      format.html{
        redirect_to lms_settings_path
      }
      format.js
    end
  end
  
  def destroy
    @leave_type.destroy
    find_leave_types
    respond_to do |format|
      format.js
    end
  end

  def index
    respond_to do |format|
      format.js
    end
  end
  
  private
  
  def find_leave_type
    @leave_type = LmsLeaveType.find_by_id(params[:id])
  end

  def lms_leave_type_params
    # params.require(:lms_leave_type).permit( :name, :days, :period, :identifier, :accountable)
    params.require(:lms_leave_type).permit!
  end
  def permit!
    each_pair do |key, value|
      convert_hashes_to_parameters(key, value)
      self[key].permit! if self[key].respond_to? :permit!
    end

    @permitted = true
    self
  end
end

app/helpers/lms_leave_types_helper.rb
module LmsLeaveTypesHelper
  def is_activated_current_year?(leave_type)
    @active_leave_types.detect {|alt| alt == leave_type}
  end
  
  def was_activated_past_years?(leave_type)
    leave_type.yearly_settings.present?
  end
end

app/views/lms_leave_types/_edit_modal.html.erb
<h3 class="title">Edit Leave Type</h3>

<%= labelled_form_for @leave_type, :remote => true do |f| %>
<%= render :partial => 'lms_leave_types/form', :locals => { :f => f } %>
  <p class="buttons">
    <%= submit_tag l(:button_update), :name => nil, :disable_with => "Updaing..." %>
    <%= submit_tag l(:button_cancel), :name => nil, :onclick => "hideModal(this);", :type => 'button' %>
  </p>
<% end %>

app/views/lms_leave_types/_form.html.erb
<%= back_url_hidden_field_tag %>
<%= error_messages_for @leave_type %>

<div class="box tabular">
<p><%= f.text_field :name, :size => 40, :required => true %></p>
<p><%= f.text_field :days, :size => 5, :required => true %></p>
<p><%= f.select :period, LmsLeaveType::PERIODS.collect {|p| [p[1], p[0]]}, :required => true %></p>
<!--<p>
  <%= label_tag :lms_leave_type_accountable, 'Accountable' %>
  <%= f.radio_button :accountable, true, :checked => f.object.accountable ? true : false %>Yes
  <%= f.radio_button :accountable, false, :checked => f.object.accountable ? false : true %>No
</p>-->
<p><%= f.text_field :identifier, :size => 10, :required => true, :disabled => @leave_type.identifier_frozen? %></p>
</div>

app/views/lms_leave_types/_index_modal.html.erb
<h3 class="title">Leave Types</h3>

app/views/lms_leave_types/_leave_types.html.erb
<% unless @yearly_settings && @yearly_settings.started %>
  <div class="box_sec">
    <div class="title">
      <h3>Leave Types</h3>
      <span><%= link_to "New type", new_lms_leave_type_path, :remote => true, :id => 'new_leave_type_link' %></span>
    </div>
    <div style="clear:both"></div>
    <% if @leave_types.present? %>
      <div class="content">
        <table>
        	<tr>
        	  <th>Name</th>
        	  <th>Days</th>
        	  <th>Period</th>
        	  <!--<th>Accountable</th>-->
  	  <th>?</th>
        	</tr>
    	<% @leave_types.each do |t| %>
        	<tr class="<%= cycle('odd', 'even') %>">
        	  <td><%= t.name %></td>
        	  <td><%= t.days %></td>
        	  <td><%= LmsLeaveType::PERIODS.detect {|p| p[0] == t.period}[1] %></td>
        	  <!--<td><%= t.accountable ? 'Yes' : 'No' %></td>-->
  	  <td>
  	    <% if is_activated_current_year?(t) %>
  	      <%= link_to 'Deactivate', deactivate_lms_leave_type_path(t)%>&nbsp;<%= link_to 'Edit', edit_lms_leave_type_path(t), :remote => true %>
  	    <% else %>
  	      <% if @yearly_settings %><%= link_to 'Activate', activate_lms_leave_type_path(t) %>&nbsp;<% end %><%= link_to 'Edit', edit_lms_leave_type_path(t), :remote => true %><% unless was_activated_past_years?(t) %>&nbsp;<%= link_to 'Delete', lms_leave_type_path(t), :method => :delete, :confirm => "If you delete it then it'll delete all the leaves, are you sure?", :remote => true %><% end %>
  	    <% end %>
  	  </td>
        	</tr>
    	<% end %>
        </table>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="box_sec">
    <div class="title">
      <h3>Leave Types</h3>
    </div>
    <div style="clear:both"></div>
    <% if @active_leave_types.present? %>
      <div class="content">
        <table>
        	<tr>
        	  <th>Name</th>
        	  <th>Days</th>
        	  <th>Period</th>
        	  <!--<th>Accountable</th>-->
        	</tr>
    	<% @active_leave_types.each do |t| %>
        	<tr class="<%= cycle('odd', 'even') %>">
        	  <td><%= t.name %></td>
        	  <td><%= t.days %></td>
        	  <td><%= LmsLeaveType::PERIODS.detect {|p| p[0] == t.period}[1] %></td>
        	  <!--<td><%= t.accountable ? 'Yes' : 'No' %></td>-->
        	</tr>
    	<% end %>
        </table>
      </div>
    <% end %>
  </div>
<% end %>

app/views/lms_leave_types/_new_modal.html.erb
<h3 class="title">New Leave Type</h3>

<%= labelled_form_for @leave_type, :remote => true do |f| %>
<%= render :partial => 'lms_leave_types/form', :locals => { :f => f } %>
  <p class="buttons">
    <%= submit_tag l(:button_create), :name => nil, :disable_with => "Creating..." %>
    <%= submit_tag l(:button_cancel), :name => nil, :onclick => "hideModal(this);", :type => 'button' %>
  </p>
<% end %>

app/views/lms_leave_types/activate.js.erb
hideModal();
$('#leave_types_frame').html('');
$('#leave_types_frame').html('<%= escape_javascript(render :partial =>'lms_leave_types/leave_types') %>');

app/views/lms_leave_types/create.js.erb
hideModal();
$('#leave_types_frame').html('<%= escape_javascript(render :partial =>'lms_leave_types/leave_types') %>');

app/views/lms_leave_types/deactivate.js.erb
hideModal();
$('#leave_types_frame').html('<%= escape_javascript(render :partial =>'lms_leave_types/leave_types') %>');

app/views/lms_leave_types/destroy.js.erb
hideModal();
$('#leave_types_frame').html('<%= escape_javascript(render :partial =>'lms_leave_types/leave_types') %>');

app/views/lms_leave_types/edit.js.erb
$('#ajax-modal').html('<%= escape_javascript(render :partial => 'lms_leave_types/edit_modal') %>');
showModal('ajax-modal', '600px');

app/views/lms_leave_types/index.js.erb
$('#ajax-modal').html('<%= escape_javascript(render :partial => 'lms_leave_types/index_modal') %>');
showModal('ajax-modal', '600px');

app/views/lms_leave_types/new.js.erb
$('#ajax-modal').html('<%= escape_javascript(render :partial => 'lms_leave_types/new_modal') %>');
showModal('ajax-modal', '600px');

app/views/lms_leave_types/update.js.erb
hideModal();
$('#leave_types_frame').html('<%= escape_javascript(render :partial =>'lms_leave_types/leave_types') %>');