config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :lms_settings do
  collection do
    get 'generate_leave_history'
  end
  member do
    get 'start'
  end
end

resources :lms_leave_accounts, :only => [:index, :create, :update]

resources :lms_dashboards do
	
end

resources :lms_reports, :only => [:index] do
  member do
  end
  collection do
    get 'month'
    get 'ytd'
    get 'year'
  end
end
get '/lms_reports/:user_id/month_detailed/:year/:month', :to => 'lms_reports#month_detailed', :as => 'month_detailed_lms_report'
get '/lms_reports/:user_id/ytd_detailed/:year/:month', :to => 'lms_reports#ytd_detailed', :as => 'ytd_detailed_lms_report'
get '/lms_reports/:user_id/year/:year', :to => 'lms_reports#year_detailed', :as => 'year_detailed_lms_report'

resources :lms_leave_types do
  member do
    get 'activate'
    get 'deactivate'
  end
end
resources :lms_leaves do
  collection do
    get 'pending'
    get 'approved'
    get 'rejected'
    get 'cancelled'
    post 'deduct'
  end
  member do
    get 'approve'
    get 'reject'
    get 'proces'
  end
end
resources :lms_public_holidays

app/controllers/lms_settings_controller.rb
class LmsSettingsController < ApplicationController
  unloadable
  include LeaveManagementSystem::Controller

  before_filter :lms_authorize
  before_filter :find_current_year_settings, :only => [:index]
  before_filter :find_leave_types, :only => [:index]
  before_filter :find_public_holidays, :only => [:index]
  
  def index
    @leave_setting = LmsLeaveSetting.first
  end
  
  def update
    @leave_setting = LmsLeaveSetting.find_by_id params[:id]
    if params[:lms_leave_setting]
      params[:lms_leave_setting][:weekends] = params[:lms_leave_setting][:weekends].present? ? params[:lms_leave_setting][:weekends].join(',') : ""
    else
      params[:lms_leave_setting] = {:weekends => ""}
    end
    attributes = params.require(:lms_leave_setting).permit(:work_from_home, :work_from_home_limit, :will_be_carry_forwarded, :max_days, :weekends)
    @leave_setting.update_attributes attributes
    redirect_to :action => :index
  end
  
  def generate_leave_history
    LmsYearlyLeaveHistory.generate_yearly_leave_history
    redirect_to :action => :index
  end
  
  def start
    @present_year_settings = LmsYearlySetting.find params[:id]
    @present_year_settings.update_attribute :started, true
    redirect_to :action => :index
  end
end

app/helpers/lms_settings_helper.rb
module LmsSettingsHelper
  include LmsLeaveTypesHelper
  
  def start_present_year_leave_tracking
    yearly_settings = LmsYearlySetting.current_year_settings
    if !yearly_settings
      link_to 'Generate Leave Accounts', generate_leave_history_lms_settings_path, :title => "Click here to generate this year leave accounts for all employees."
    elsif !yearly_settings.started?
      link_to 'Start Tracking', start_lms_setting_path(yearly_settings), :title => "Click here to start the system to allow the employees to apply leaves. Before start the system, activate the needed leave types and common settings for this year.", :confirm => "Are every settings configured needed for this year? Once you started the system, no settings can be modified."
    else
      link_to "Manage Leave Accounts", lms_leave_accounts_path
    end
  end
  
  def groups(role)
    Group.where(["id in (?)", LeaveManagementSystem.allocated_groups(role)]).map(&:name).join(', ')
  end
end

app/views/lms_settings/_generic_settings.html.erb
<% weekends = @leave_setting.weekends.split(',').map {|w| w.to_i} %>
<%= form_tag("/lms_settings/#{@leave_setting.id}", :method => :put) do |f| %>
  <% unless @yearly_settings && @yearly_settings.started %>
    <div class="field_wrapper">
      <label>Do you have Work From Home policy?</label>
      <span><%= radio_button_tag "lms_leave_setting[work_from_home]", true, @leave_setting.work_from_home ? true : false, :class => 'lms_ls_wfh' %> Yes <%= radio_button_tag "lms_leave_setting[work_from_home]", false, @leave_setting.work_from_home ? false : true, :class => 'lms_ls_wfh' %> No</span>
      <div style="clear:both;"></div>
      <div class="field_wrapper sub_field_wrapper <%= @leave_setting.work_from_home ? '' : 'hide' %>">
        <label>Limit per Month</label>
        <span><%= text_field_tag "lms_leave_setting[work_from_home_limit]", @leave_setting.work_from_home_limit, :disabled => !@leave_setting.work_from_home %></span>
      </div>
    </div><br/>
    <div class="field_wrapper">
      <label>What to do the not used leaves at the end of the year?</label>
      <span><%= radio_button_tag "lms_leave_setting[will_be_carry_forwarded]", true, @leave_setting.will_be_carry_forwarded ? true : false, :class => 'lms_ls_cf' %> Carry Forward <%= radio_button_tag "lms_leave_setting[will_be_carry_forwarded]", false, @leave_setting.will_be_carry_forwarded ? false : true, :class => 'lms_ls_cf' %> Cash Back</span>
      <div style="clear:both;"></div>
      <div class="field_wrapper sub_field_wrapper <%= @leave_setting.will_be_carry_forwarded ? '' : 'hide' %>" id="leave_setting_max_days">
        <label>Max. no of days will be carry forwarded</label>
        <span><%= text_field_tag "lms_leave_setting[max_days]", @leave_setting.max_days, :disabled => !@leave_setting.will_be_carry_forwarded %></span>
      </div>
    </div><br/>
  <% else %>
    <div class="field_wrapper">
      <label>Work from home allowed? How many days?</label>
      <span><% if @yearly_settings.work_from_home %>Yes, <%= @yearly_settings.work_from_home_limit %> day(s) per month<% else %>No<% end %></span>
      <div style="clear:both;"></div>
    </div><br/>
    <div class="field_wrapper">
      <label>Will unused leaves be Carry forwarded or Cash backed?</label>
      <span><% if @yearly_settings.carry_forward %>Maximum <%= @yearly_settings.carry_forward_limit %> day(s) will be carry forwarded.<% else %>Will be cash backed.<% end %></span>
      <div style="clear:both;"></div>
    </div><br/>
  <% end %>
  <div class="field_wrapper">
    <label>Weekends</label>
    <div style="clear:both;"></div>
    <div class="field_wrapper sub_field_wrapper">
      <% LmsLeaveSetting::WEEKDAYS.each_with_index do |day, index| %>
      <span><%= check_box_tag "lms_leave_setting[weekends][]", index, weekends.include?(index) %> <%= day %></span>
      <% end %>
    </div>
  </div><br/>
  <div class="field_wrapper">
    <span class="form_submit"><%= submit_tag "Update" %></span>
  </div>
<% end %>

app/views/lms_settings/_public_holidays.html.erb
  <div class="box_sec">
    <div style="clear:both"></div>
    <% if @public_holidays.present? %>
      <div class="content">
        <table>
        	<tr>
        	  <th>Occasion name</th>
        	  <th>Date</th>
  	  <th>?</th>
        	</tr>
    	<% @public_holidays.each do |h| %>
        	<tr class="<%= cycle('odd', 'even') %>">
        	  <td><%= h.occ_name %></td>
        	  <td><%= h.ph_date.strftime "%b %d, %Y" %></td>
        	  <td><%= link_to 'Edit', edit_lms_public_holiday_path(h), :remote => true %>&nbsp;<%= link_to 'Remove', lms_public_holiday_path(h), :method => :delete, :confirm => "Is it not a public holiday?", :remote => true %></td>
        	</tr>
    	<% end %>
        </table>
      </div>
    <% else %>
      <div class="content">
        <p class="nodata">No holidays</p>
      </div>
    <% end %>
  </div>

app/views/lms_settings/_roles.html.erb
<table>
  <thead>
    <tr>
      <th>Role</th>
      <th>Assigned Group</th>
    </tr>
  </thead>
  <tbody>
    <% LeaveManagementSystem::ROLES.each do |key, role| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td><b><%= role.capitalize %></b></td>
        <td><%= groups(role) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/lms_settings/index.html.erb
<%= render :partial => "/partials/top_menu" %>
<div id="lms_box1" class="lms_box">
  <div class="box_title">
    <% if @yearly_settings.present? %><div id="new_public_holiday_link"><%= link_to "Add Holiday", new_lms_public_holiday_path, :remote => true %></div><% end %>
    <h2>Public Holidays <%= Date.today.year %></h2>
  </div>
  <div class="box_content">
    <div id="public_holidays_frame">
      <%= render :partial => "public_holidays" %>
    </div>
  </div>
</div>

<div id="lms_box2" class="lms_box">
  <div class="box_title"><h2>Leave types & <%= Date.today.year %> settings</h2></div>
  <div class="box_content">
    <div id="lms-accounts-menu">
      <%= start_present_year_leave_tracking %>
    </div>
    <div id="leave_types_frame">
      <%= render :partial => "lms_leave_types/leave_types" %>
    </div>
    <div class="box_sec">
      <div class="title">
        <h3>Leave Settings</h3>
	<span></span>
      </div>
      <div style="clear:both"></div>
      <div class="content" id='leave-settings-wrapper'>
	<%= render :partial => "generic_settings" %>
      </div>
    </div>
    <div class="box_sec">
      <div class="title">
        <h3>Roles</h3>
	<span></span>
      </div>
      <div style="clear:both"></div>
      <div class="content" id='lms-roles-wrapper'>
	<%= render :partial => "roles" %>
      </div>
    </div><br/>
    <div>
    </div>
  </div>
</div>