config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :lms_settings do
  collection do
    get 'generate_leave_history'
  end
  member do
    get 'start'
  end
end

resources :lms_leave_accounts, :only => [:index, :create, :update]

resources :lms_dashboards do
	
end

resources :lms_reports, :only => [:index] do
  member do
  end
  collection do
    get 'month'
    get 'ytd'
    get 'year'
  end
end
get '/lms_reports/:user_id/month_detailed/:year/:month', :to => 'lms_reports#month_detailed', :as => 'month_detailed_lms_report'
get '/lms_reports/:user_id/ytd_detailed/:year/:month', :to => 'lms_reports#ytd_detailed', :as => 'ytd_detailed_lms_report'
get '/lms_reports/:user_id/year/:year', :to => 'lms_reports#year_detailed', :as => 'year_detailed_lms_report'

resources :lms_leave_types do
  member do
    get 'activate'
    get 'deactivate'
  end
end
resources :lms_leaves do
  collection do
    get 'pending'
    get 'approved'
    get 'rejected'
    get 'cancelled'
    post 'deduct'
  end
  member do
    get 'approve'
    get 'reject'
    get 'proces'
  end
end
resources :lms_public_holidays

app/models/lms_leave_type.rb
class LmsLeaveType < ActiveRecord::Base
  unloadable
  include Redmine::SafeAttributes
  
  #PERIODS = [[0,'Yearly'],[1, 'Quarterly'],[2, 'Monthly']]
  PERIODS = [[0,'Yearly']]
  YEAR = :y
  QUARTER = :q
  MONTH = :m
  IDENTIFIER_MAX_LENGTH = 20
  
  has_many :lms_custom_fields
  has_and_belongs_to_many :yearly_settings, :class_name => "LmsYearlySetting", :join_table => 'lms_leave_types_lms_yearly_settings'
  
  validates_presence_of :name, :days, :period, :identifier
  validates_uniqueness_of :name, :identifier
  validates_length_of :name, :maximum => 40
  #validates_format_of :days, :with => /^[0-9]*\.?[0-9]+$/
  validates_numericality_of :days, :only_integer => true, :greater_than => 0
  validates_length_of :identifier, :in => 2..IDENTIFIER_MAX_LENGTH
  validates_format_of :identifier, :with => /\A[a-z]+_*[a-z]+\Z/, :if => Proc.new { |t| t.identifier_changed? }
  
  safe_attributes 'name', 'days', 'period', 'accountable', 'identifier'
  
  after_create :create_custom_fields
  after_destroy :delete_custom_fields
  after_update :update_present_year_leave_history
  
  def identifier_frozen?
    errors[:identifier].blank? && !(new_record? || identifier.blank?)
  end
   
  private
  def create_custom_fields
    raw_sql = "ALTER TABLE #{LmsYearlySetting.table_name} ADD COLUMN tot_#{identifier} DECIMAL(7,2) DEFAULT 0;"
    ActiveRecord::Base.connection.execute(raw_sql)
    raw_sql = "ALTER TABLE #{LmsYearlyLeaveHistory.table_name} ADD COLUMN tot_#{identifier} DECIMAL(7,2) DEFAULT 0;"
    ActiveRecord::Base.connection.execute(raw_sql)
    raw_sql = "ALTER TABLE #{LmsMonthlyLeaveHistory.table_name} ADD COLUMN ded_#{identifier} DECIMAL(7,2) DEFAULT 0;"
    ActiveRecord::Base.connection.execute(raw_sql)
    raw_sql = "ALTER TABLE #{LmsLeaveStatus.table_name} ADD COLUMN ded_#{identifier} DECIMAL(7,2) DEFAULT 0;"
    ActiveRecord::Base.connection.execute(raw_sql)
    ActiveRecord::Base.connection.close
    lms_custom_fields.build({:table_name => LmsYearlySetting.table_name, :column_name => "tot_#{identifier}"}).save
    lms_custom_fields.build({:table_name => LmsYearlyLeaveHistory.table_name, :column_name => "tot_#{identifier}"}).save
    lms_custom_fields.build({:table_name => LmsMonthlyLeaveHistory.table_name, :column_name => "ded_#{identifier}"}).save
    lms_custom_fields.build({:table_name => LmsLeaveStatus.table_name, :column_name => "ded_#{identifier}"}).save
    reload_schema
  end
  
  def delete_custom_fields
    lms_custom_fields.each do |cf|
     raw_sql = "ALTER TABLE #{cf.table_name} DROP COLUMN #{cf.column_name};"
     ActiveRecord::Base.connection.execute(raw_sql)
     cf.destroy
    end
    ActiveRecord::Base.connection.close
    reload_schema
  end
    
  def update_present_year_leave_history
    if days_changed?
      year_settings = LmsYearlySetting.current_year_settings
      if year_settings
        if year_settings.leave_types.where(["lms_leave_type_id = ?", self.id]).first
           year_settings.update_leave_type self
	end
      end
    end
  end
  
  def reload_schema
    ["LmsYearlySetting", "LmsYearlyLeaveHistory", "LmsMonthlyLeaveHistory", "LmsLeaveStatus"].each {|class_name| Object.const_get(class_name).reset_column_information}
  end
end

app/controllers/lms_leaves_controller.rb
class LmsLeavesController < ApplicationController
  unloadable
  include LeaveManagementSystem::Controller

  before_filter :lms_authorize
  before_filter :find_common_settings, :only => [:new, :create]
  before_filter :find_current_month_leave_history, :only => [:new, :create]
  before_filter :find_current_year_leave_history, :only => [:new, :create]
  before_filter :find_current_year_settings, :only => [:new, :create, :proces, :deduct, :update]
  before_filter :find_leave_types, :only => [:proces, :deduct]
  before_filter :find_public_holidays, :only => [:new, :create]

  def new
    @leave = LmsLeave.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @leave = @employee.lms_leaves.build :lms_yearly_leave_history_id => @current_month_leave_history.lms_yearly_leave_history_id, :lms_monthly_leave_history_id => @current_month_leave_history.id
    @leave.safe_attributes = lms_leave_params
    if @leave.valid?
      monthly_history = LmsMonthlyLeaveHistory.where(:user_id => @current_month_leave_history.user_id,
                                                     :lms_yearly_leave_history_id => @current_month_leave_history.lms_yearly_leave_history_id,
                                                     :month => params[:lms_leave][:from_date].to_date.month).first
      unless monthly_history
        @leave.errors.add :base, "You can't apply leave in #{params[:lms_leave][:from_date].to_date.strftime '%B'} month"
        respond_to do |format|
          format.js {render :action => :new}
        end && return
      else
        @leave.lms_monthly_leave_history_id = monthly_history.id
      end
    end
    if @leave.save
      @pending_leaves = Employee.pending_leaves
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.js {render :action => :new}
      end
    end
  end

  def edit
  end

  def update

  end

  def destroy
    leave = LmsLeave.find_by_id params[:id]
    leave_status = leave.lms_leave_status
    if leave_status.pending?
      leave_status.update_attributes :status => LmsLeaveStatus::CANCELLED, :cancelled_on => Time.now
    end
    @pending_leaves = Employee.pending_leaves
    respond_to do |format|
      format.js
    end
  end

  def approve
    leave = LmsLeave.find_by_id params[:id]
    leave_status = leave.lms_leave_status
    if leave_status.pending?
      leave_status.update_attributes :status => LmsLeaveStatus::APPROVED, :approved_by => @employee.id, :approved_on => Time.now
    end
    @pending_leaves = LmsLeave.pending_leaves
    params[:menu] = 'Others'
    respond_to do |format|
      format.html {redirect_to :controller => :lms_dashboards, :action => :index, :menu => params[:menu], :tab => 'pending'}
      format.js {}
    end
  end

  def reject
    leave = LmsLeave.find_by_id params[:id]
    leave_status = leave.lms_leave_status
    if leave_status.pending?
      leave_status.update_attributes :status => LmsLeaveStatus::REJECTED, :rejected_by => @employee.id, :rejected_on => Time.now
    end
    @pending_leaves = LmsLeave.pending_leaves
    params[:menu] = 'Others'
    respond_to do |format|
      format.html {redirect_to :controller => :lms_dashboards, :action => :index, :menu => params[:menu], :tab => 'pending'}
      format.js
    end
  end

  def proces
    unless request.xhr?
      redirect_to :controller => :lms_dashboards, :action => :index, :menu => 'Others', :tab => 'approved', :id => params[:id]
    else
      @leave = LmsLeave.find_by_id params[:id]
      @applier = @leave.employee
      @leave_history = @applier.leave_history(@active_leave_types.map(&:identifier), Date.today.year, 12) unless LmsLeaveCategory::WORK_FROM_HOME[@leave.leave_category_id]
      respond_to do |format|
        format.js
      end
    end
  end

  def deduct
    leave = LmsLeave.find_by_id params[:lms_leave_status][:lms_leave_id]
    if leave.lms_leave_status.approved?
      if LmsLeaveCategory::WORK_FROM_HOME[leave.leave_category_id]
        leave.lms_leave_status.update_attributes(:ded_wfh => leave.no_of_days, :status => LmsLeaveStatus::PROCESSED, :processed_by => @employee.id, :processed_on => Time.now)
      else
        attributes = params[:lms_leave_status].merge(:status => LmsLeaveStatus::PROCESSED, :processed_by => @employee.id, :processed_on => Time.now)
        unless leave.lms_leave_status.update_attributes(update_lms_leave_params(attributes))
          @leave = leave
          @applier = @leave.employee
          @leave_history = @applier.leave_history(@active_leave_types.map(&:identifier), Date.today.year, 12)
          respond_to do |format|
            format.js {render :action => :proces}
          end && return
        end
      end
    end
    params[:menu] = params[:menu] || 'Others'
    if params[:menu] == 'Others'
      @approved_and_processed_leaves = LmsLeave.approved_and_processed_leaves
    else
      @approved_and_processed_leaves = Employee.approved_and_processed_leaves
    end
    respond_to do |format|
      format.js
    end
  end

  def index
  end

  def pending
    if params[:menu] == 'Others'
      @pending_leaves = LmsLeave.pending_leaves
    else
      @pending_leaves = Employee.pending_leaves
    end
    respond_to do |format|
      format.js
    end
  end

  def approved
    if params[:menu] == 'Others'
      @approved_and_processed_leaves = LmsLeave.approved_and_processed_leaves
    else
      @approved_and_processed_leaves = Employee.approved_and_processed_leaves
    end
    respond_to do |format|
      format.js
    end
  end

  def rejected
    if params[:menu] == 'Others'
      @rejected_leaves = LmsLeave.rejected_leaves
    else
      @rejected_leaves = Employee.rejected_leaves
    end
    respond_to do |format|
      format.js
    end
  end

  def cancelled
    if params[:menu] == 'Others'
      @cancelled_leaves = LmsLeave.cancelled_leaves
    else
      @cancelled_leaves = Employee.cancelled_leaves
    end
    respond_to do |format|
      format.js
    end
  end

  private
  def find_common_settings
    @lms_settings = LmsLeaveSetting.first
  end

  def find_current_month_leave_history
    @current_month_leave_history = @employee.current_month_leave_history
  end

  def find_current_year_leave_history
    @current_year_leave_history = @employee.current_year_leave_history
  end

  def update_lms_leave_params(params)
    # params.permit(:lms_leave_id, :lop, :ded_wfh, :ded_carry_forward, :ded_casualleave, :ded_sickleave, :ded_compoff, :ded_privilegeleave, :status, :processed_by, :processed_on)
    params.permit!
  end

  def lms_leave_params
    # params.require(:lms_leave).permit(:user_id, :leave_category_id, :lms_yearly_leave_history_id, :lms_monthly_leave_history_id, :leave_category_id, :notificants, :parent_leave_id, :from_date, :to_date, :no_of_days, :reason , :reported_to=> [],:leave_dates_object=> [])
    params.require(:lms_leave).permit!
  end
  def permit!
    each_pair do |key, value|
      convert_hashes_to_parameters(key, value)
      self[key].permit! if self[key].respond_to? :permit!
    end

    @permitted = true
    self
  end
end

app/helpers/lms_leaves_helper.rb
module LmsLeavesHelper
  def leaves_to_be_detected tot_leaves, ded_leaves, nol
    if nol < (tot_leaves - ded_leaves)
      (0..nol).step(0.5)
    else
      (0..(tot_leaves - ded_leaves)).step(0.5)
    end
  end
  
  def available_leaves tot_leaves, ded_leaves
    tot_leaves - ded_leaves
  end
  
  def reporting_managers
    current_user = Employee.current
    current_year_leave_history = current_user.current_year_leave_history
    if current_year_leave_history.reporter.to_i.zero?
      LeaveManagementSystem.active_employees_with_role(LeaveManagementSystem::ROLES[:ar]).select {|manager| manager != current_user}
    else
      manager = User.find current_year_leave_history.reporter.to_i
      LeaveManagementSystem.active_employees_with_role(LeaveManagementSystem::ROLES[:ar]).select {|ma| ma.id == manager.id}
    end
  end
end

app/views/lms_leaves/_leave_history.html.erb
<% menu = params[:menu] || 'Own' %>
<% unless params[:tab] %>
  <% pending_tab = ['index', 'create', 'pending', 'destroy', 'approve', 'reject'].include?(action_name) %>
  <% approved_tab = ['approved', 'deduct'].include?(action_name) %>
  <% rejected_tab = ['rejected'].include?(action_name) %>
  <% cancelled_tab = ['cancelled'].include?(action_name) %>
<% else %>
  <% pending_tab = params[:tab] == 'pending' %>
  <% approved_tab = params[:tab] == 'approved' %>
  <% rejected_tab = false %>
  <% cancelled_tab = false %>
<% end %>
  <div class="box_title">
    <% if LeaveManagementSystem.allowed_to?(@employee, LeaveManagementSystem::ROLES[:ar])%>
      <span id="dashboard_menu_wrapper">
      <ul id="dashboard_menu">
        <li class="own <%= menu == 'Own' ? 'active' : 'inactive' %>"><div>Own</div><span></span></li>
        <li class="others <%= menu == 'Others' ? 'active' : 'inactive' %>"><span></span><div>Others</div></li>
      </ul>
      </span>
    <% end %>
    <h2>Leave History <%= today.year %></h2>
  </div>
  <div class="box_content">
   <div id="lms_top_menu" class='leave_history_menu'>
     <ul>
       <li class="<%= pending_tab ? 'active' : '' %>"><%= link_to('Pending', pending_lms_leaves_path(:menu => menu), :remote => true) %></li>
       <li class="<%= approved_tab ? 'active' : '' %>"><%= link_to('Approved', approved_lms_leaves_path(:menu => menu), :remote => true) %></li>
       <li class="<%= rejected_tab ? 'active' : '' %>"><%= link_to('Rejected', rejected_lms_leaves_path(:menu => menu), :remote => true) %></li>
       <li class="<%= cancelled_tab ? 'active' : '' %>"><%= link_to('Cancelled', cancelled_lms_leaves_path(:menu => menu), :remote => true) %></li>
     </ul>
   </div>
   <div id="leave_history">
      <% if leaves.present? %>
      <table>
        <tr>
	  <% if menu == 'Others' %><th>Applier</th><% end %>
  	  <th>No Of Days</th>
	  <th>Reason</th>
	  <th>From</th>
	  <th>To</th>
	  <th>Leave type</th>
	  <th>Applied To</th>
	  <th>Applied on</th>
	  <% if menu == 'Others' %>
	    <% if pending_tab %>
	      <th>What to do?</th>
	    <% elsif approved_tab %>
	      <th>What to do?</th>
	      <th>Approver</th>
	      <th>Approved on</th>
	      <th>Processor</th>
	      <th>Processed on</th>
	    <% elsif rejected_tab %>
	      <th>Rejector</th>
	      <th>Rejected on</th> 
	    <% elsif cancelled_tab %>
	      <th>Cancelled on</th>
	    <% end %>
	  <% else %>
	    <% if pending_tab %>
	      <th>What to do?</th>
	    <% elsif approved_tab %>
	      <th>Status</th>
	      <th>Approver</th>
	      <th>Approved on</th>
	      <th>Processor</th>
	      <th>Processed on</th>
	    <% elsif rejected_tab %>
	      <th>Rejector</th>
	      <th>Rejected on</th>
	    <% elsif cancelled_tab %>
	      <th>Cancelled on</th>
	    <% end %>
	  <% end %>
        </tr>
	<% leaves.each do |leave| %>
        <tr class="<%= cycle('odd', 'even') %>">
	  <% if menu == 'Others' %><td><%= leave.emp_name %></td><% end %>
  	  <td><%= truncate_trailing_zero(leave.no_of_days) %></td>
	  <td><%= leave.reason %></td>
	  <td><%= leave.from_date.strftime("%d %b %Y") %></td>
	  <td><%= leave.to_date.strftime("%d %b %Y") %></td>
	  <td><%= LmsLeaveCategory.all[leave.leave_category_id] %></td>
	  <td><%= leave.reportees %></td>
	  <td><%= leave.created_at.strftime("%d %b %Y") %></td>
  	  <% if menu == 'Others' %>
	    <% if leave.pending? %>
	      <td>
	        <% if LeaveManagementSystem.allowed_to?(@employee, LeaveManagementSystem::ROLES[:dt]) && !leave.reported_to.include?(@employee.id.to_s) %>
	          <p style='color:red;'>Yet to approve</p>
	        <% else %>
	          <%= link_to 'Approve', approve_lms_leafe_path(leave.id), :remote => true %>
	          <%= link_to 'Reject', reject_lms_leafe_path(leave.id), :remote => true  %>
	        <% end %>
	      </td>
	    <% elsif leave.approved? %>
	      <td>
	        <% if LeaveManagementSystem.allowed_to? @employee, LeaveManagementSystem::ROLES[:dt] %>
	          <% if leave.id == leave.parent_leave_id %>
	            Process
		  <% else %>
		    <%= link_to 'Process', proces_lms_leafe_path(leave.id), :remote => true %>
		  <% end %>
		<% else %>
		  <p style='color:red;'>Yet to process</p>
		<% end %>
	      </td>
	      <td><%= leave.approver_name %></td>
	      <td><%= leave.approved_on.strftime("%d %b %Y") %></td>
	      <td>--</td>
	      <td>--</td>
	    <% elsif leave.processed? %>
	      <td><p style='color:green;'>Processed</p></td>
	      <td><%= leave.approver_name %></td>
	      <td><%= leave.approved_on.strftime("%d %b %Y") %></td>
	      <td><%= leave.processor_name %></td>
	      <td><%= leave.processed_on.strftime("%d %b %Y") %></td>
	    <% elsif leave.rejected? %>
	      <td><%= leave.lms_leave_status.rejector.name %></td>
	      <td><%= leave.rejected_on.strftime("%d %b %Y") %></td>
	    <% elsif leave.cancelled? %>
	      <td><%= leave.cancelled_on.strftime("%d %b %Y") %></td>
	    <% end %>
	  <% else %>
	    <% if leave.pending? %>
	      <td><%= link_to 'Cancel', lms_leafe_path(leave.id), :method => :delete, :remote => true, :confirm => "Are you sure to cancel your leave?" %></td>
	    <% elsif leave.approved? %>
	      <td>
		<% if LeaveManagementSystem.allowed_to?(@employee, LeaveManagementSystem::ROLES[:dt]) %>
	          <% if leave.id == leave.parent_leave_id %>
	            Process
		  <% else %>
		    <%= link_to 'Process', proces_lms_leafe_path(leave.id, :menu => 'Own'), :remote => true %>
		  <% end %>
		<% else %>
	          <p style='color:red;'>Yet to process</p>
		<% end %>
	      </td>
	      <td><%= leave.approver_name %></td>
	      <td><%= leave.approved_on.strftime("%d %b %Y") %></td>
	      <td>--</td>
	      <td>--</td>
	    <% elsif leave.processed? %>
	      <td><p style='color:green;'>Processed</p></td>
	      <td><%= leave.approver_name %></td>
	      <td><%= leave.approved_on.strftime("%d %b %Y") %></td>
	      <td><%= leave.processor_name %></td>
	      <td><%= leave.processed_on.strftime("%d %b %Y") %></td>
	    <% elsif leave.rejected? %>
	      <td><%= leave.lms_leave_status.rejector.name %></td>
	      <td><%= leave.rejected_on.strftime("%d %b %Y") %></td>
	    <% elsif leave.cancelled? %>
	      <td><%= leave.cancelled_on.strftime("%d %b %Y") %></td>
	    <% end %>
	  <% end %>
        </tr>
	<% end %>
      </table>
      <% else %>
        <span>None to display</span>
      <% end %>
   </div>
  </div>
  
<script>
$(document).ready(function(){
	$('table tr.odd, table tr.even').click(function(){
		$('table tr.odd.selected-row, table tr.even.selected-row').removeClass('selected-row');
		$(this).addClass('selected-row');
	});
    <% if params[:tab] && params[:tab] == 'approved' && params[:id] %>
      $('#leave_history a[href="<%= proces_lms_leafe_path(params[:id]) %>"]').click();
    <% end %>
	$("#dashboard_menu li.inactive span").click(function(){
		var menu = $(this).siblings().text();
		$.ajax({
			url: '/lms_leaves/pending',
			method: 'get',
			data: {'menu':menu},
			success: function(data){
			}
		});
	});
});
</script>

app/views/lms_leaves/_proces_modal.html.erb
<div id='detailed-report'>
  <div id='heading'>
    <h3 class='title'>Deduct Leave</h3>
  </div>
  <div id='emp-info' class='box'>
    <h3>Applier Info</h3>
    <div><span>Name </span><%= @applier.name %></div>
    <% if @applier.respond_to? :department %><div><span>Department </span><%= @applier.department.name %></div><% end %>
    <% if @applier.respond_to? :job_title %><div><span>Designation </span><%= @applier.job_title %></div><% end %><br/>
  </div>
  <div id='leave-detail' class='box'>
    <h3>Leave Detail</h3>
    <div id='leave-summ'>
      <div><span>Type of leave </span><%= LmsLeaveCategory.all[@leave.leave_category_id] %></div>
      <div><span>No of days </span><%= truncate_trailing_zero(@leave.no_of_days) %></div>
      <div>
        <span>Applied dates </span>
	<% full_days = @leave.leave_dates_object.select {|date| date.match /:F$/} %>
	<% half_days = @leave.leave_dates_object.select {|date| date.match /:H$/} %>
	<% if full_days.present? %>
	  <b>Full Days:</b> <%= full_days.map {|date| date.to_date.strftime("%d %b %Y")}.join(', ') %><br/>
	<% end %>
	<% if half_days.present? %>
	  <b>Half Days:</b> <%= half_days.map {|date| date.to_date.strftime("%d %b %Y")}.join(', ') %>
	<% end %>
      </div>
      <div><span>Reason </span><%= @leave.reason %></div>
      <br/>
    </div>
  </div>
  <div class='box'>
    <h3>Deduction Form</h3>
    <%= labelled_form_for @leave.lms_leave_status, :url => deduct_lms_leaves_path,method: :post, :remote => true do |f| %>
    <%= f.hidden_field :lms_leave_id, :value => @leave.id %>
    <%= hidden_field_tag(:menu, params[:menu]) if params[:menu] %>
    <div id='ded_leave_error' style='color:red;'><%= @leave.lms_leave_status.errors.full_messages[0] %></div>
    <div id='deduction_form'>
      <% if @yearly_settings.carry_forward && available_leaves(@leave_history.tot_carry_forward, @leave_history.ded_carry_forward) > 0 %>
        <label>Carry Forward</label> <%= select f.object_name, "ded_carry_forward", leaves_to_be_detected(@leave_history.tot_carry_forward, @leave_history.ded_carry_forward, @leave.no_of_days).to_a %></br>
      <% end %>
      <% @active_leave_types.each do |lt| %>
        <% if available_leaves(@leave_history.send("tot_#{lt.identifier}"), @leave_history.send("ded_#{lt.identifier}")) > 0 %>
          <label><%= lt.name %></label> <%= select f.object_name, "ded_#{lt.identifier}", leaves_to_be_detected(@leave_history.send("tot_#{lt.identifier}"), @leave_history.send("ded_#{lt.identifier}"), @leave.no_of_days).to_a %></br>
        <% end %>
      <% end %>
        <label>LOP</label> <%= select f.object_name, "lop", (0..@leave.no_of_days).step(0.5).to_a %> </br>
    <div id='tot_ded_leaves'><label><b>Deducted Leaves</b></label> <span style='color:red;'>0</span></div>
    </div>
      <p class="buttons">
        <%= submit_tag l(:button_process), :name => nil, :disable_with => "Processing..." %>
        <%= submit_tag l(:button_cancel), :name => nil, :onclick => "hideModal(this);", :type => 'button' %>
      </p>
    <% end %>
  </div>
</div>

<script>
  var applied_leaves = <%= @leave.no_of_days %>;
  var sum_of_ded_leaves = 0;
  $("input[type='submit']").click(function(){
 	 sum_of_ded_leaves =0;
 	 var ded_leaves = $("#deduction_form select");
 	 ded_leaves.each(function(index){
 		 sum_of_ded_leaves += Number($(this).val());
 	 });
 	 if(sum_of_ded_leaves != applied_leaves){
 		 $('#ded_leave_error').text('Deducted leaves are not matching with applied leaves. Please check the deducted leaves');
 		 return false;
 	 }
  });
  
  $("#deduction_form select").change(function(){
 	 sum_of_ded_leaves =0;
 	 $('#deduction_form select').each(function(index){
 		 sum_of_ded_leaves += Number($(this).val());
 	 });
 	 $('#tot_ded_leaves span').text(sum_of_ded_leaves);
 	 if(sum_of_ded_leaves != applied_leaves){
 		 $('#tot_ded_leaves span').css('color', 'red');
 	 }
 	 else{
 		 $('#tot_ded_leaves span').css('color', 'green');
 	 }
  });
</script>

app/views/lms_leaves/approve.js.erb
$('.dashboard #lms_box1').html('<%= escape_javascript(render :partial => 'leave_history', :locals => {:today => Date.today, :leaves => @pending_leaves}) %>');

app/views/lms_leaves/cancelled.js.erb
$('.dashboard #lms_box1').html('<%= escape_javascript(render :partial => 'leave_history', :locals => {:today => Date.today, :leaves => @cancelled_leaves}) %>');

app/views/lms_leaves/create.js.erb
hideModal();
$('.dashboard #lms_box1').html('<%= escape_javascript(render :partial => 'leave_history', :locals => {:today => Date.today, :leaves => @pending_leaves}) %>');

app/views/lms_leaves/deduct.js.erb
hideModal();
$('.dashboard #lms_box1').html('<%= escape_javascript(render :partial => 'leave_history', :locals => {:today => Date.today, :leaves => @approved_and_processed_leaves}) %>');

app/views/lms_leaves/destroy.js.erb
$('.dashboard #lms_box1').html('<%= escape_javascript(render :partial => 'leave_history', :locals => {:today => Date.today, :leaves => @pending_leaves}) %>');

app/views/lms_leaves/new.js.erb
$('#ajax-modal').html('<%= escape_javascript(render :partial => 'lms_leaves/new_modal') %>');
showModal('ajax-modal', '700px');

app/views/lms_leaves/pending.js.erb
$('.dashboard #lms_box1').html('<%= escape_javascript(render :partial => 'leave_history', :locals => {:today => Date.today, :leaves => @pending_leaves}) %>');

app/views/lms_leaves/proces.js.erb
<% if LmsLeaveCategory::WORK_FROM_HOME[@leave.leave_category_id] %>
  $('#ajax-modal').html('<%= escape_javascript(render :partial => 'lms_leaves/proces_wfh_modal') %>');
<% else %>
  $('#ajax-modal').html('<%= escape_javascript(render :partial => 'lms_leaves/proces_modal') %>');
<% end %>
showModal('ajax-modal', '600px');

app/views/lms_leaves/reject.js.erb
$('.dashboard #lms_box1').html('<%= escape_javascript(render :partial => 'leave_history', :locals => {:today => Date.today, :leaves => @pending_leaves}) %>');